#!/usr/bin/env python3
"""Write a Hummingbot controller YAML from a backtest JSON or CLI params.

Keeps zipline/pandas research out of the live Gateway process.
"""

from __future__ import annotations

import argparse
import json
import sys
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from orca_tight_range.logic import Params, params_to_dict  # noqa: E402

TEMPLATE = """\
# Generated by research/zipline_to_gateway_bridge.py — do not hand-edit race params
# without recording the change in docs/TRIALS_LEDGER.md

controller_name: orca_tight_range
controller_type: generic
connector_name: {connector_name}
lp_provider: orca/clmm
trading_pair: SOL-USDC
pool_address: "{pool_address}"
total_amount_quote: {capital}
side: RANGE
range_width_pct: {range_width_pct}
skew_bias: {skew_bias}
rebalance_trigger_pct: {rebalance_trigger_pct}
volatility_exhaustion_window_s: {volatility_exhaustion_window_s}
max_rebalances_per_hour: {max_rebalances_per_hour}
stop_loss_drawdown_pct: {stop_loss_drawdown_pct}
"""


def params_from_backtest(path: Path) -> Params:
    payload = json.loads(path.read_text())
    raw = payload.get("params", payload)
    return Params(
        range_width_pct=Decimal(str(raw["range_width_pct"])),
        skew_bias=Decimal(str(raw["skew_bias"])),
        rebalance_trigger_pct=Decimal(str(raw["rebalance_trigger_pct"])),
        volatility_exhaustion_window_s=int(raw.get("volatility_exhaustion_window_s", 300)),
        max_rebalances_per_hour=int(raw.get("max_rebalances_per_hour", 6)),
        capital_allocation_usdc=Decimal(str(raw.get("capital_allocation_usdc", "800"))),
        stop_loss_drawdown_pct=Decimal(str(raw.get("stop_loss_drawdown_pct", "15"))),
    )


def render(params: Params, pool_address: str, connector_name: str) -> str:
    d = params_to_dict(params)
    return TEMPLATE.format(
        connector_name=connector_name,
        pool_address=pool_address,
        capital=d["capital_allocation_usdc"],
        **d,
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--from-json", type=Path, help="data/last_backtest.json")
    parser.add_argument("--pool-address", default="", help="Orca SOL/USDC Whirlpool address")
    parser.add_argument("--connector", default="solana-mainnet-beta")
    parser.add_argument(
        "--out",
        type=Path,
        default=ROOT / "configs" / "orca_tight_range.yml",
    )
    args = parser.parse_args()
    params = params_from_backtest(args.from_json) if args.from_json else Params()
    text = render(params, args.pool_address, args.connector)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
